### ISSUE TITLE
EventListener.php와 Setting.yml(설정)을 이제 제대로 만들어야 할 것 같네요.

### ISSUE THREAD

**Issue by Potatoshare88** [MPMDevelopers/MPMLand#10]
해야할 것
1. 블록 부시거나 설치할 때 자신의 섬이면 허용, 아니면 비허용
2. PVP On/Off
3. 물위인지 그냥 공중섬인지
4. 땅과 섬 값
5. Prefix설정(이건 약간 하기 싫은..

**Comment by djdisodo** [comment]
섬에 기본상자 내용물 (상자의 NBT코드를 별도의 저장된 json파일에서 불러와서 적용하는게 어떨까요?)

**Comment by djdisodo** [comment]
이거 서버키고보니까 settings.yml내용물이 아무것도 안들어있네요...
