### ISSUE TITLE
[건의]몇가지 건의사항 나무관련,명령어 추가관련

### ISSUE THREAD

**Issue by djdisodo** [MPMDevelopers/MPMLand#16]
나무 처리를 pocketmine\level\generator\object\Tree 로 하는게 어떨까요?
(나무에 꽤나 공들이신것 같은데.....)
/섬 홈
명령어(마지막에 방문한 섬으로 이동)을 추가하는게 어떨까요?

**Comment by Potatoshare88** [comment]
일단 제대로 개발뒤에 부가 기능 요청 받겠습니다^^ 일단 아이디어 주셔서 감사합니다!

**Comment by Potatoshare88** [comment]
이 기능은 다른 플긴에서 구현을 충분히 할 수 있다고 판단되어서 클로즈 합니다.
