### ISSUE TITLE
섬 오류

### ISSUE THREAD

**Issue by shdudwns** [MPMDevelopers/MPMLand#18]
![screenshot_2017-11-03-00-53-28](https://user-images.githubusercontent.com/26038520/32336022-86d6af90-c031-11e7-8c2a-c8884d05d565.png)

**Comment by Potatoshare88** [comment]
오 마이 갓!! 아무래도 설정.yml을 잘못 하다보니 그렇게 된 것 같네요.. 수정하겠습니다.

(/섬 구매나 /섬 이동은 잘 되나요?)

**Comment by shdudwns** [comment]
명령어는 되는데 쓰면 서버가 먹통
