### ISSUE TITLE
명령어부분을 제작성 하는거는 어떨까요?

### ISSUE THREAD

**Issue by shdudwns** [MPMDevelopers/MPMLand#28]
현제 해보는중인데.... /섬 구매 시 섬 번호랑 섬생성 소스좀 알수있나오?

**Comment by shdudwns** [comment]
모카님은 반복문에서 일어난다하고...
솔로님은 backtrace를 올려보세요
이렇게 답변옴

**Comment by Potatoshare88** [comment]
솔로님의 도움으로 메소드를 사용하는데 그때 루프가 일어나여서 솔로님께서 그 루프 문제를 해결하셨습니다.
