### ISSUE TITLE
/섬구매 칠시 island섬을 구매해야되는데 이상함

### ISSUE THREAD

**Issue by shdudwns** [MPMDevelopers/MPMLand#31]
구매를 치면 island월드 섬을 구매해야되는데 이상하게 다른 월드가 구매가 됩니다
그리고 서버 재붓하고나면 번호가 초기화되서 겹칩니다
@solo5star @Potatoshare88

**Comment by Potatoshare88** [comment]
현재 오류 고치는 중..

**Comment by Potatoshare88** [comment]
정확히 스샷으로 보내주세요.. 숫자 꼬이는거는 고쳐서 상관 없고..

**Comment by shdudwns** [comment]
@Potatoshare88 island섬이 아니라 이상한 월드가 구매

**Comment by shdudwns** [comment]
![screenshot_2017-11-06-17-02-20](https://user-images.githubusercontent.com/26038520/32430853-6c96ec54-c314-11e7-820c-b02b870d2a65.png)

**Comment by shdudwns** [comment]
섬이동할시 여기로옴

**Comment by shdudwns** [comment]
@Potatoshare88

**Comment by Potatoshare88** [comment]
음.. 월드 이동 처리 분명이 한것 같은데.. 어떻게 된 걸 까요..
